spring:
  application:
    name: CommunitysAdministrativeSystem
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/communitysadministrativesystem?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: he12345678
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: 
        - classpath:/static/
        - classpath:/public/
        - classpath:/resources/
        - classpath:/META-INF/resources/
        - file:${user.dir}/uploads/
  servlet:
    context-path: /
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8085

mybatis:
  type-aliases-package: com.hjh.communitysadministrativesystem.Entity
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false

logging:
  level:
    root: info
    com.hjh.communitysadministrativesystem.dao: trace
    org.springframework.jdbc: trace

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql